### ISSUE TITLE
Move component tests out of src

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#10]
_From @pameck on March 31, 2016 10:40_

_Copied from original issue: rabblerouser/rabblerouser-core-fork#9_

**Comment by yearofthedan** [comment]
Is this an issue? I find it very useful the keep the tests with the src in React.

**Comment by camjackson** [comment]
We've actually been going in the opposite direction with the frontend code lately. I.e., moving the tests downwards, to be closer to their corresponding modules.
