### ISSUE TITLE
Write some onboarding documentation with links for key concepts

### ISSUE THREAD

**Issue by phazel** [rabblerouser/core#124]
When people join, we'd like for them to have some familiarity with the concepts we're using, so that they can participate in conversations. This might help with making the project feel more inclusive for people as they come onboard. Something like "We'd like for you to read about these things before you get involved."

Topics like:
- Microservices
- Event sourcing
- Serverless architecture
- Some basics of various tech we're using: Docker, Kinesis, Javascript, Node, React, Lambda, etc.

This would be good to have in our docs repo, so that it's easy for us to add to it as we go, keeping an eye out for any links we might send to new people as we onboard them.

**Comment by camjackson** [comment]
Moved to https://github.com/rabblerouser/rabblerouser-docs/issues/1
