### ISSUE TITLE
Introduce redux for a cleaner frontend

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#13]
_From @pameck on March 31, 2016 11:1_
- [x] Redux boilerplate on signup app
- [x] Redux boilerplate on admin app
- [x] Redux boilerplate on super admin app
- [x] Redux + saga on branches view
- [x] Redux + saga on groups view
- [x] Redux + saga on members view
- [x] Redux + saga on admins view

_Copied from original issue: rabblerouser/rabblerouser-core-fork#12_

**Comment by yearofthedan** [comment]
Still some gaps with test coverage, particularly on integration, but these can be filled as the relevant areas are touched ongoing

**Comment by camjackson** [comment]
Awesome work!
