### ISSUE TITLE
Event persistence

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#133]
Some event streams, like kafka, can be configured to keep events forever (until you run out of disk space). Kinesis can only keep events in the stream for up to 7 days, and by default only 24 hours. We need a way to store events forever, and a way for services to page through the full historical event stream. This is currently the biggest missing piece of our event streaming solution.

Acceptance criteria:
 - [x] All events are stored forever
 - [x] When a service starts up, it can page through all the events, in order, until the present moment
 - [x] After that, the service can then receive all new events coming down the stream
 - [x] There should be no gap between the last event read from the historical record, and the first event received on the stream. I.e. don't drop any events
 - [x] Once an event is read from the historical record, it should not be received from the stream. I.e. don't double-handle any events
 - [x] When paging through historical events, we should get the same retry logic as described in #132.

**Comment by camjackson** [comment]
Possible solution - just pipe everything to an S3 bucket. When initialising a the stream client to listen for events, it checks the bucket first, and keeps track of the kinesis shard iterator as it does so. Once it exhausts the bucket, it can then switch to the stream, skipping over any events that are older than the last one it read from the bucket.

**Comment by camjackson** [comment]
One example of how to write a kinesis stream to an S3 bucket: https://aws.amazon.com/blogs/big-data/persist-streaming-data-to-amazon-s3-using-amazon-kinesis-firehose-and-aws-lambda/

This one is going via kinesis firehose though. We may not want to involve yet another AWS service to make it work.

**Comment by camjackson** [comment]
I've begun some work on this. There's an event-archiver repo [here](https://github.com/rabblerouser/event-archiver) which saves all events on a kinesis stream to an S3 bucket. Inside the bucket there will be a object created for each UTC hour. When the lambda receives events from kinesis, it either writes them to the existing object if there is one, or it creates a new object if it's the first event received for the current hour.

The next step would be to change the stream-client so that when subscribing to a stream, it goes to the bucket first and pages through all of the events, before listening for new events coming directly off the stream. We also need logic to make sure that we don't double-handle (or zero-handle) events that are visible both in S3 and kinesis simultaneously. Both the event-forwarder and the event-archiver should be giving the stream-client enough kinesis event metadata for this to be possible.

**Comment by akjones** [comment]
Should clients really know about the bucket? If we have to worry about double handling from both kinesis and s3, then we might run into trouble. Single source of truth and all that.

In the future we're going to have to configure the system to replay all events (for instance, recovering from a full outage), so would we be better to make apps treat events as replayable (in such a way that we don't retrigger successful one-off events like emails). Are we better off investing in making it easy to replay the whole event stream from the beginning of time (with some sort of rollup/snapshot mechanism if startup time gets really slow). This would be really good for resilience.

**Comment by akjones** [comment]
It might be a case of being able to selectively replay a stream via a client so we can re/build apps as being a good thing to do as well. 

Though I'm mostly uneasy about having the clients (which seem to be thought of as part of apps) knowing about the event stream/storage mechanism.

**Comment by camjackson** [comment]
To clarify stream-client is an npm library that abstracts the whole idea of the stream away from the actual application. Currently you just do `myStreamClient.consumer.on('member-registration', memberService.createMember` or something like that. And that will set it up so that incoming events from the stream, of that event type, get passed to that function.

What I was proposing is that when you bind that handler, the stream-client would first go and page through the bucket, before opening itself up to brand new events from the stream. And the library would also be able to inspect events from the bucket and from the stream, and make sure it doesn't call the handling function twice. All of this would be totally invisible to the app - all that the app would know is that events come from the client library, without needing to care about whether they're archived events from a bucket, or new events from the stream.

So to come back to your question about caring about the bucket, multiple event sources etc: Somebody needs to care about that problem, because kinesis can't do persistence. So we need a way of providing access to historical events.

In terms of idempotence, yes, we need a way to not replay old events for e.g. things that send emails. That could just be a flag when you initialise the stream-client library, which says "only send me new events, skip the step of paging through historical ones first".

**Comment by camjackson** [comment]
I'm totally open to having that knowledge of event streaming/storage etc being pulled out of the stream-client library. Do you have thoughts on where else it could be done?

**Comment by camjackson** [comment]
Also on slack, @phazel asked: 

> That thing you mentioned about the stream-client checking the bucket before accepting new events, how does that work as we scale? Is that a convention?
> Do all the lambdas do that?

The checking of the bucket would only be when an application is starting up and needs to initialise. So it shouldn't happen constantly. App startup time is definitely something we'd need to keep an eye on as the number of historical events grows.

**Comment by camjackson** [comment]
I have a version of this that seems mostly functional. It needs more manual verification, which I can't really do until #123 is merged. Once that happens and I have a chance to test it some more, it'll need a technical review to make sure the approach isn't totally bonkers. Also there's a bit more work to make it function locally. It looks like https://github.com/lphoward/fake-s3 may work really well for that.
