### ISSUE TITLE
Move from SnapCI to a new CI provider as Snap is going away

### ISSUE THREAD

**Issue by akjones** [rabblerouser/core#134]
SnapCI is going away (https://blog.snap-ci.com/blog/2017/02/06/2017-02-06-snap-announcement/) and we need to keep automated builds going.

We need to choose a new tool and move the build for this repo to it.

Needs to be done by end of May at the latest.

- [x] Pick a new provider
- [x] core
- [x] mailer
- [x] stream-client
- [x] event-forwarder
- [x] event-archiver

**Comment by camjackson** [comment]
Have experimented with Travis and Circle so far.

Travis currently up and running for core: https://travis-ci.org/rabblerouser/core

Circle is also generally very good, but there are some issues with docker support. A big update (Travis 2.0) is coming soon which will apparently give much better docker stuff, so may be worth visiting then.

No other repos have been converted yet.
