### ISSUE TITLE
Ultimate bikeshed - project naming convention

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#136]
Right now most of our projects are in the form `rabblerouser/rabblerouser-something`. However, at least one is just `rabblerouser/event-archiver`, without the extra RR in the name. This came up on slack, with comments from @akjones, @phazel, and @yearofthedan, but there was no consensus. It would be good to figure this out before we start migrating away from Snap, just in case repo renaming causes issues there (we know it confused Snap in the past).

<img width="689" alt="screen shot 2017-02-13 at 11 00 06 pm" src="https://cloud.githubusercontent.com/assets/1930451/22882646/3c1813dc-f240-11e6-94bd-dd38c599bab0.png">

:bike: :bike: :bike: :bike: :bike:

**Comment by camjackson** [comment]
Just want to point out that the repo names don't necessarily need to exactly match published names. E.g. on github we might have `rabblerouser/stream-client`, which we could publish to npm as `rabblerouser-stream-client` so that the context is clear. Although now I think about it, npm supports namespaced packages too, so we could equally publish as `@rabblerouser/stream-client`. Things that get published as docker images likewise could be `rabblerouser/mailer` both on github and on the docker hub.

**Comment by akjones** [comment]
I'm happy with relying on the github org name for repos, so `rabblerouser/stream-client` would be fine, as long as artifacts get stored in the public repos with `rabblerouser` as either a namespace, or repository name or as a prefix if the artifact repository doesn't have the concept of a namespace.

**Comment by camjackson** [comment]
I think that's close enough to having a consensus. I'm going to make this change now, so that we get it out of the way *before* potentially lots of new people join in tomorrow, only to have things shift from underneath them.
