### ISSUE TITLE
Receive an email in SES and post it to the group-mailer service

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#140]
When an admin sends an email to `[groupid]@[rabblerouser-instance-url]`, the [group-mail-receiver](https://github.com/rabblerouser/group-mail-receiver) lambda should pick this up and send a POST request to the [`group-mailer`](https://github.com/rabblerouser/group-mailer) service. Refer #160 for the overall design and context.

- [ ] The lambda should be triggered by any email sent to `<any email address>@rabblerouser-instance-url`.
- [ ] The lambda should make an HTTP `POST /mail` to the group-mailer
- [ ] The POST body should contain
  - [ ] The `from:` field of the email (will be used for auth in the future)
  - [ ] The `to:` field of the email (will be used to figure out who to forward it to)
  - [ ] The S3 bucket/object, or ARN, where the full email data can be found

See the notes in the [mailer](https://github.com/rabblerouser/mailer) repo for how to get started with verifying senders and receivers with SES)

**Comment by akjones** [comment]
This is not the thing that authenticates the email request. To start with the group mailer will authenticate it, and we have the option of moving it out later.
