### ISSUE TITLE
Convert branch persistence to event sourcing

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#145]
Currently some of our data is stored using events, and some of it is in a relational database. This task is to store branches using events.

**Comment by pameck** [comment]
This is  a drawing of how creating/updating/deleting a branch works with events. 
![branches-with-events](https://cloud.githubusercontent.com/assets/3664374/24573986/a7812a6c-16d7-11e7-8cca-fb9a5675a25e.png)

**Comment by pameck** [comment]
This is a drawing of how creating/updating/deleting a branch works with events.
![branches-with-events](https://cloud.githubusercontent.com/assets/3664374/24574034/a5a2ddd4-16d8-11e7-9627-cf0522499d4b.png)
