### ISSUE TITLE
s/lab-assistant/rabble-rouser

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#16]
_From @akjones on April 11, 2016 9:19_
- [x] Replace mentions of "labs" with "branches"
- [x] Replace mentions of "participants" with "members"
- [x] `labSelection` => `branchSelection` (field names, variables, CSS id selector)
- [x] Rename variables etc in `strings.js`

_Copied from original issue: rabblerouser/rabblerouser-core-fork#15_

**Comment by camjackson** [comment]
@akjones Not sure what the scope of this card should be.

Firstly, is this only user-facing strings, or should this also include renaming variables, functions, tables, etc.

Secondly, does the existing model of membership still work, and if so, what are the right terms? Does a Lab become a branch?

**Comment by akjones** [comment]
this was meant to be an internal rename, ensuring vars & functions and stuff are all updated. user facing stuff can be done here, or they can be picked up in one of the config cards.

internally, labs were always called branches (at model level anyways), so we shouldn't need to update much there (it anything). the structure of the membership (members are in branches and groups, and groups are in branches, and branches are in a network (which in a pseudo element, just the collection of everything).

does that make sense? parent brain doesn't translate tech well sometimes...

**Comment by camjackson** [comment]
Yeah I think that makes sense. There's definitely a lot of frontend code like `labValidator`, `getLabGroups`,  `getLabParticipants`, etc.

**Comment by camjackson** [comment]
I've started work on this. The backend is all done, except for `config/db.json`, because I figured that will break people's dev environments, and it would also need to be updated in the ops code. And I didn't really want to go delving into the ops stuff just yet.

**Comment by camjackson** [comment]
I'm going to call this done for now. All of the app code is done AFAICT.

There's some stuff in the provisioning and db config files that still refers to the lab, but that's a bit trickier because it might break people's environments. There's probably a bunch of breaking changes coming soon anyway when we bring in EventStore and Docker and Kubernetes, so I'd be inclined to clean the last of it up at that point. I'll open a new issue for that.
