### ISSUE TITLE
Email everyone in an organisation

### ISSUE THREAD

**Issue by phazel** [rabblerouser/core#160]
**As a super admin, I want to email everyone in my organisation, so I can mobilise them.**

WHEN I send an email to everyone@my-org.click,
THEN it gets sent to all members.

Out of scope:
 - Authorisation,
 - Obscuring the special email address
 - Groups

We're doing a simpler version which is just about sending to everyone in an organisation, and then extending it to groups later. For now we're ignoring groups.

Glorious architecture diagram of great justice:

![img_20170614_180357](https://user-images.githubusercontent.com/1930451/27641716-44c3b760-5c4f-11e7-9676-41b64b69b71d.jpg)

Clockwise from top-left:

1.  Someone sends an email to the special email address, which is received by SES.
2. #161 SES uploads the email content into an S3 bucket
3. #140 SES invokes a lambda (the [group-mail-receiver](https://github.com/rabblerouser/group-mail-receiver)) with the email metadata
4. #140 The group-mail-receiver sends an HTTP POST to the [group-mailer](https://github.com/rabblerouser/group-mailer).
5. #141 The group-mailer resolves the 'everyone' request into a concrete list of members, which it is able to do because it listens for events such as `member-registered`, etc.
6. #141 The group-mailer puts a `send-email` event onto the stream, which includes a reference to the S3 object, but not the full email body
7. #163 The [mailer](https://github.com/rabblerouser/mailer) receives the event via the its [event-forwarder](https://github.com/rabblerouser/event-forwarder) lambda.
8. #163 The mailer retrieves the full email data from S3, and sends the email to everyone listed in the event, via SES.
9. #163 (not shown) The mailer puts success/failure events back on the stream.

**Comment by camjackson** [comment]
Treating this as the meta-issue to track progress on this feature. I wanted to use a milestone, but milestone descriptions don't seem to support proper markdown so the formatting was all whacked.

**Comment by camjackson** [comment]
Slightly updated diagram (main difference is that the `group-mail-receiver` is triggered by S3, not SES: 
![img_0145](https://user-images.githubusercontent.com/1930451/28618730-04516d90-7238-11e7-85a9-8bdb6ef1d2b0.JPG)

**Comment by camjackson** [comment]
It works!
