### ISSUE TITLE
Replace Jasmine for mocha/chai/sinon (backend for now)

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#19]
_From @pameck on April 18, 2016 13:22_

_Copied from original issue: rabblerouser/rabblerouser-core-fork#18_

**Comment by camjackson** [comment]
_From @pameck on April 18, 2016 14:11_
- [x] Add a global file to avoid repetitive requires in specs (add it to the task definition)
- [x] rename all temp things
- [x] remove jasmine.json (the frontend does not need it)
- [x] create helper for cleaning up the db
- [x] change mocha reporter
- [ ] the new test task takes ages to run (the compiler maybe?)

**Comment by elimydlarz** [comment]
Only one assignee, but... I'm helping.

**Comment by pameck** [comment]
Done with this!
