### ISSUE TITLE
Remove eslint exceptions for no-param-reassign

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#26]
There are currently 3 places where we have exceptions to the [no-param-reassign](http://eslint.org/docs/rules/no-param-reassign) rule (i.e. param mutation).
- [ ] [`sortColumn.js`](https://github.com/rabblerouser/rabblerouser-core/blob/master/src/frontend/lib/sortColumn.js) - Mutates several properties on params.
- [ ] [`ParticipantsList.jsx`](https://github.com/rabblerouser/rabblerouser-core/blob/master/src/frontend/components/admin/participantView/ParticipantsList.jsx#L88) - Calls the above, and then does more param mutation. Not 100% sure, but it looks like this might actually be mutating props? 😱 
- [ ] [`ParticipantsViewContainer`](https://github.com/rabblerouser/rabblerouser-core/blob/master/src/frontend/components/admin/participantView/ParticipantsViewContainer.jsx#L44) - Again, not totally sure, but it looks like this is directly mutating state, in addition to calling `setState`.

There's not much testing on these three modules, so I was hesitant to change them without fully understanding the implications. Would be good if someone who knows this part of the code had a closer look. Perhaps @danmutton or @rdoh?

**Comment by elimydlarz** [comment]
There are many more cases of this on the backend. I'll tell eslint to ignore them for now, but whoever picks this up might want to fix them too =)

**Comment by camjackson** [comment]
I can't find any of these any more. They must have been fixed.
