### ISSUE TITLE
Strip the membership sign up form back to basics

### ISSUE THREAD

**Issue by akjones** [rabblerouser/core#30]
- [x] Remove school question
- [x] Remove lab to join question
- [x] Keep one of participant name OR contact name - no need for both
- [x] Change year of birth to date of birth

**Comment by kalsop** [comment]
- Remove school question
- Remove lab to join question
- Keep one of participant name OR contact name - no need for both
- Change year of birth to date of birth
- "Register for" + name of org

**Comment by camjackson** [comment]
Should this card be limited to just the signup form? For every field that's removed from the signup form, there's also the server side code, the DB model, and then of course in the admin UI there's all the forms for editing those fields.

Feels weird to take out the school field (for example) form the signup, but leave it there on the admin side. I think I'll probably take it out of everywhere.

**Comment by yearofthedan** [comment]
Good point my only concern is that it's a pretty big story. Could split them into separate stories for each field.

**Comment by camjackson** [comment]
Good idea. I'm still figuring out how big it is. If it's getting out of hand, I'll split it.

**Comment by camjackson** [comment]
Does anyone know: Is there a reason we ask for first and last name? As opposed to just name?

**Comment by yearofthedan** [comment]
I think it was a requirement on one or both implementations, but I recall we had discussions about it being biased and limiting. Can we leave it up to front-ends to decide how to represent names and store it as one field?

**Comment by camjackson** [comment]
I guess. For this particular frontend that I'm looking at right now, I'd be inclined to do a single field (and then store it like that). 

One good reason that I can think of for splitting it is so you can address emails to people by their first name. But for that purpose I'd be more inclined to ask for full name and preferred name.

I'm also a little unclear on removing the branch (formerly lab) selection box. I know that we don't really need it for HFP, but it seems like an important thing for many of our target organisations. Perhaps we take the form field out, but leave it as a DB field. In the future it might be filled via a dropdown, or based on your address, etc etc.

Hmm, this card is slightly trickier than I anticipated...

**Comment by camjackson** [comment]
I've spun out a separate issue for removing (hiding) the branch dropdown box: #62.

**Comment by camjackson** [comment]
One more question about this: What do we want to do about the contact phone number?

At the moment it's a compulsory field, which doesn't seem right Hack for Privacy's purposes. I'm not sure if it even makes sense to have it there for HFP at all?

Trying to figure out whether I should leave it as is, or make it optional, or take it out altogether, or just hide it on the frontend but leave everything else there... Thoughts @akjones?

**Comment by camjackson** [comment]
Also I was chatting with Dan last night and we were considering ripping out the 'additional info' field as well.

**Comment by akjones** [comment]
I'd make phone number optional. Hack for Privacy won't ask for it, but it'll be useful if folks provide it. Other orgs will want it for sure.
