### ISSUE TITLE
choose an event store & implement in the vagrant dev setup so we can start using it

### ISSUE THREAD

**Issue by akjones** [rabblerouser/core#36]
Current contenders: 
- https://geteventstore.com - open source, custom event sourcing solution, relatively easy operational concerns
- AWS DynamoDB - proprietary, but much less management overhead than anything we'd run ourselves, especially when scaling, would have to be coerced into being an event store
- https://couchdb.apache.org/ - has been around a long time, can be coerced in a similar way to dynamodb, i have no idea about its operational complexity.

**Comment by elimydlarz** [comment]
I played with EventStore quite a bit (we were hoping to go all eventy for something and were stranded on the beach trying things out) and was very impressed. I'm keen to try it out for integrating LTTE and RR core, though I don't know enough about either to know exactly what needs integrating.

**Comment by camjackson** [comment]
Good to know @elimydlarz. The first step for integrating would probably be to get it working in our dev setup (which is what I think this card is about?). @akjones mentioned that he'd been able to get it running in a docker container today.

**Comment by camjackson** [comment]
Going to close this issue seeing as we're currently trying out kinesis. This was more of a meta-issue anyway.
