### ISSUE TITLE
Prevent admins from removing themselves

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#4]
_From @pameck on March 31, 2016 10:32_

Admins can lock themselves out, we need to either prevent this or warn them loudly. 

_Copied from original issue: rabblerouser/rabblerouser-core-fork#3_

**Comment by bfinney-thoughtworks** [comment]
What's a sequence to reliably reproduce this behaviour?

**Comment by camjackson** [comment]
Fixed in #185
