### ISSUE TITLE
Fix flaky heroku deployments

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#48]
A little while ago I changed the root package.json so that building and copying the frontend assets is a `prestart` rather than a `postinstall:frontend`. https://github.com/rabblerouser/rabblerouser-core/commit/9df3f9e4fc97faaaf0b965d0cf7560becb6c5909#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R11

This makes it so that the backend always has the most up-to-date frontend assets when doing `npm start` from the root of the repo, rather than just what was compiled when you first did `npm install` in the root of the repo. This makes the dev experience simpler and more reliable. Yay!

Unfortunately, Heroku expects you to do such tasks as part of your install command, rather than your start command, which kind of makes sense. If the compilation process takes too long, then Heroku gives us error R10- Boot Timeout: https://devcenter.heroku.com/articles/error-codes#r10-boot-timeout.

This doesn't happen all the time, and the workaround is to restart the app until it happens to boot quick enough, but this is obviously not ideal.
## 

The easiest fix is to change the root `prestart` task back to `postinstall:frontend`, but that makes the dev experience worse. Specifically, it means that people who are working on the backend and don't care about what's going on with the frontend assets, will need to keep track of when they last did `npm run build` from the root of the repo, and know when to run it again.

I'm not sure what a better fix is, but I'm sure there is one!

**Comment by pameck** [comment]
The problem was that building the app in "prestart" made Heroku timed out and therefore broke the build. I moved "npm run build" to "postinstall", which also makes it easier for people who are setting up the project for the first time.
