### ISSUE TITLE
evaluate victorykit for possible adoption into rabble rouser

### ISSUE THREAD

**Issue by akjones** [rabblerouser/core#51]

**Comment by akjones** [comment]
VictoryKit does petitions, emails about petitions all with a/b testing and tracking of everything. It was not super trivial to get up and running though.

Looks like it was designed to integrate with CRMs, so that could make it a good candidate for adoption.

**Comment by tomsulston** [comment]
This is a hint: when building a new service, is it easier to start with VictoryKit?
