### ISSUE TITLE
Remove the final references to the lab

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#55]
There are a few things left over from #16 in the provisioning code, and in the db config variables. These can probably be cleaned out when we start bringing in whacky things like Docker, Kubernetes, and EventStore.

**Comment by camjackson** [comment]
We probably don't need this for the initial release? Especially if we pick it up as part of the Docker/Kubernetes/EventStore work.

**Comment by pameck** [comment]
removed final references to the lab.
