### ISSUE TITLE
Branch admins should get a notification when a new participant joins

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#6]
_From @pameck on March 31, 2016 10:36_

_Copied from original issue: rabblerouser/rabblerouser-core-fork#5_

**Comment by phazel** [comment]
MVP is CCing the branch admin for the confirmation email the new member receives.

**Comment by phazel** [comment]
Or like... BCC? (Rob)

**Comment by pameck** [comment]
Done, the admins get a copy of the email sent to the member.
