### ISSUE TITLE
as a branch admin i want to be able to export my branch data so i can import it into another system (to send email to segments of my members)

### ISSUE THREAD

**Issue by akjones** [rabblerouser/core#64]

**Comment by camjackson** [comment]
Just making sure I understand the scope of this one - Is it basically to export all of the groups and members for a specific branch? Does a JSON file download fit the bill?

**Comment by akjones** [comment]
Most mail providers (e.g. Mailchimp) expect import as excel or csv. I suggest we start with csv.

**Comment by akjones** [comment]
And include everything we have for members in the branch, so segmenting can be done in that other system.

**Comment by akjones** [comment]
We can add respond to requests for other export formats later on via the `accepts` header.
