### ISSUE TITLE
Members should received a confirmation email after joining a branch

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#7]
When a member signs up, they should receive and email confirming their new membership.

Ideally from and return address, subject and email body should be configurable.

_From @pameck on March 31, 2016 10:37_

_Copied from original issue: rabblerouser/rabblerouser-core-fork#6_

**Comment by tomsulston** [comment]
MVP for Ticket #6 is (B)CCing the branch admin for the confirmation email the new member receives.

**Comment by pameck** [comment]
Done!! We will add the branch admin to bcc as part of issue #6
