### ISSUE TITLE
EPIC: Make the UI nicer

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#75]
- Signup form
- Admin view

**Comment by camjackson** [comment]
Might be a good idea to spin out stories from this epic. But I'm not sure what they should be.

**Comment by megtw** [comment]
@yearofthedan want to make a time to pair on this sometime soon?

**Comment by camjackson** [comment]
This card is a bit weird. Are we able to break it down into stories we can play? Either way I'd like to move it out of 'doing'.

The signup UI is a bit nicer now, from #73. It would be good to make the admin UI match the new style. I might do that as part of #74?

**Comment by yearofthedan** [comment]
Let's spin off some stories from here to work on.
The following smallish discrete stories come to mind:

1. removing any style bootstrapping libraries and replacing with our own styles (I'd also remove sass unless there's a compelling reason to keep it).
2. not quite a ux thing, and dependent upon the first but review and remove unrequired id/name/class attributes in the app. Most of these were used with bootstrap / css things and may be redundant.
3. splitting the network and branch sections to provide a clearer mental model for users
4. removing modal flows and replacing with inline editing
5. locating success and error messaging with their triggering components
6. adding hover / highlight effects to icons and buttons
7. adding loading indicators when requests in progress (possibly on a button)
8. adding some basic a11y support (use a a11y lib for linting, add tab indexing and keyboard use)

Also not sure what we talked about regarding the custom styles, but I think that custom styling the admin app (and whatever level of complexity we want for it) is a low priority compared to the above. 
 
Any opinions on validity or priority?

I'll create the stories once I hear back some opinions.

**Comment by camjackson** [comment]
Great idea. In assigning myself to this, I was really just picking up the first one.

I think 1 pretty much entails a rewrite of the styles, so it's probably easiest to do 2 at the same time.

We should already get `eslint-plugin-jsx-a11y` from `eslint-config-airbnb`, but there's definitely more we can do.

RE custom styles - I already added basic support for this in d049fd2, because it gave me an easy way to swap styles out. Almost like a feature toggle while the rewrite is in progress.

Happy for this issue to be closed, and for me to be assigned to the first 1 / 2 points.

**Comment by camjackson** [comment]
Replaced with:

#113 - remove stylesheets, bourbon, classnames
#114 - split the admin and network admin views
#115 - remove the modals
#116 - Put success/error messages near their actions
#117 - Loading indicators
#118 - A11y

Haven't done anything for the hover/highlight one, as I thought we already had that? Feel free to open an issue for it if there are places it's missing.

**Comment by camjackson** [comment]
Tagging @yearofthedan just to make sure he sees the question in my previous comment RE hover/highlight stuff.

**Comment by yearofthedan** [comment]
I think hover/highlight is okay actually. There are some inconsistencies, but they can be covered off as part of style migration.
