### ISSUE TITLE
Rename 'pastoral notes' to 'notes'

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#76]
The 'pastoral notes' field is left over from the lab. The ability to add notes to members may still be useful for admins, however, so we should leave it in and just rename it.

It would be good to rename it in user-facing bits, and also the rest of the code (e.g. DB columns).

**Comment by rammy4real** [comment]
hello camjackson. good day. hope you are doing great sir. i would love to contribute to this. just to let you know my skills
     html:
     css
     javascript: basic/beginner
     java: basic/beginner
 really do love to be part of your team. promise to give my best and all .
thank you sir.
rammy4real@gmail.com

**Comment by camjackson** [comment]
Hey there @rammy4real, and welcome. We'd love to have you contribute to the project. I believe no one has started work on this issue yet, so feel free to have a go at it if you like.

Let us know if you need any help getting started :)
