### ISSUE TITLE
As an admin, I want to collect my members' addresses, so that I can target campaigns based on location

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#77]
Location-based campaigning is just one example of how it can useful to know where your members live.

We should already have a lot of the code in place for storing and handling member addresses, as it was something we needed for a previous version of the project. However, we took it out as part of #30. 

For the organisations we're targeting next, address will be a very obvious omission if we don't have it visible on the UI, so we'd like to bring it back. _But_, we have an existing client organisation who don't really need people's address.

So ideally it would be possible for each organisation to configure whether or not the address field is shown on the UI (both on the signup page, and in the admin app). For an example of how we already allow different organisations to customise the app, see [this part](https://github.com/rabblerouser/rabblerouser-core#customising-the-app-for-your-organisation) of the readme. And look the code from these search queries:
[ORG_NAME](https://github.com/rabblerouser/rabblerouser-core/search?utf8=%E2%9C%93&q=ORG_NAME&type=Code), [orgName](https://github.com/rabblerouser/rabblerouser-core/search?utf8=%E2%9C%93&q=orgName&type=Code).

That particular pattern is how we've been customising things so far. Eventually we want a nice GUI where end users can click to toggle things on and off, but we're not there yet, and this works for now.

**Comment by camjackson** [comment]
Looks like @asnr and @letitia-may are going to take a look at this. I'll add more info to the card so that it's a bit clearer what needs to be done.

**Comment by asnr** [comment]
Yep, @letitia-may and/or I will try and get started today. Thanks for fleshing out the issue!

**Comment by Letitia-May** [comment]
Hi, it looks like in the code that both residential and postal address have been used in the past. Should we be including both for this story? If we include only one address, should we write to the residential or postal address section in the database? Thanks!

**Comment by camjackson** [comment]
That's a good question. Thoughts, @akjones?

**Comment by akjones** [comment]
Organisations with any kind of electoral function (eg political parties, unions) require residential address, but postal address gives folks more privacy. We only need one set of address fields for the showcase in Barcelona, so let's write it to postal address, and we can add the other one in later.

**Comment by Letitia-May** [comment]
Hi, we have two questions. Address will be customisable and it's currently set up so that address is not enabled as the default and therefore does not show. Is this ok or should it be enabled as the default? Also, if address is enabled, should those fields be mandatory? Thanks :)

**Comment by camjackson** [comment]
Not enabled by default sounds good.

If we go by the theory of only asking for stuff that you absolutely need (and @akjones point that some orgs have a legal requirement to collect address), then perhaps make it mandatory if it's on. Although, will that make the validation logic more complex? Because you need to make it mandatory/optional based on whether it's enabled? As opposed to just always being optional. Shouldn't be too tricky, but if it's going to be a pain, then we could probably make it always optional for now.

A lot of this may change once we implement a full dynamic custom signup form system, where orgs have full flexibility to specify what they need to collect.

**Comment by camjackson** [comment]
We have a 'review' column in huboard, but I think the PR process kind of covered that. So I'll just move this to done.
