### ISSUE TITLE
`npm run seed` fails for new installs

### ISSUE THREAD

**Issue by asnr** [rabblerouser/core#83]
I followed the first time install steps in the README:

``` sh
$ git clone https://github.com/rabblerouser/rabblerouser-core.git
$ cd rabblerouser-core
$ vagrant up
$ vagrant ssh
vagrant$ npm install
vagrant$ npm test
```

The tests passed without any problems. I then tried to run the seed script:

``` sh
vagrant$ npm run seed
```

This failed with the error `Error: SequelizeDatabaseError: relation "Branches" does not exist`.

I then ran several other scripts I found in the repo in this order:

``` sh
vagrant$ node backend/node_scripts/seed/dummyMemberWithGroup.js
vagrant$ node backend/node_scripts/seed/dummyBranchWithGroups.js
vagrant$ node backend/node_scripts/createSuperAdmin.js
vagrant$ node backend/node_scripts/e2e-seed/branch-group-member-organiser.js
```

after which I was able to run `npm run seed` without any problems. My guess is that `npm run seed` failed because at that stage the database didn't have any tables at all, and one of the scripts above created them, after which `npm run seed` was able to drop the tables and repopulate them.

**Comment by pameck** [comment]
Yeah :( .. But if you do npm start first, it will work. Worth having that in the readme until we fix this properly. 

Npm start creates the db schema, which is the problem when running the seeding first, the schema is not there.

**Comment by yongpeishi** [comment]
`npm start` does migration and seed. README is now updated to remove unnecessary seeding step. We can close this issue?

**Comment by camjackson** [comment]
Yep, thanks!
