### ISSUE TITLE
The request for branches on the registration form returns too much information

### ISSUE THREAD

**Issue by yearofthedan** [rabblerouser/core#87]
The api returns a list of branches with which to populate the select field for the signup form. This payload includes additional details such as contact information which is currently only available in the admin view and not required for signup. 

We should update the endpoint (or create a new one if it is shared) to return only the information required by the form.

**Comment by camjackson** [comment]
More info: 

- [Here](https://github.com/rabblerouser/rabblerouser-core/blob/master/frontend/src/signup/components/DetailsForm.jsx#L39) is the select box that shows the list of branches for new signups to pick from. Note that it only shows if there's more than one branch present, and it looks like it only need the branch IDs and names.
- [Here](https://github.com/rabblerouser/rabblerouser-core/blob/master/frontend/src/signup/sagas.js#L12) is the saga that fetches that data
- [Here](https://github.com/rabblerouser/rabblerouser-core/blob/557eb1366f63b8133ae67733519da18ae914cbfd/backend/src/routes/index.js#L26) is the relevant API route, which currently returns *all* information about the branches.
- [Here](https://github.com/rabblerouser/rabblerouser-core/blob/master/frontend/src/admin/actions.js#L24) is where the admin dashboard fetches branches. It's actually a different endpoint, which is good.
- [Here](https://github.com/rabblerouser/rabblerouser-core/blob/master/backend/src/routes/index.js#L38) is that admin endpoint- this shouldn't need changing

I think really all that this issue needs is for the unauthenticated `/branches` endpoint to limit the info it returns.

**Comment by camjackson** [comment]
Fixed in #92.
