### ISSUE TITLE
As an organisation, I want to automatically create the infrastructure needed for my Rabble Rouser

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#89]
I.e. terraform.

**Comment by akjones** [comment]
What's the scope of this card? It seems to cross over with #66, #67 and #68.

**Comment by akjones** [comment]
We should also talk about what the infra should look like.

**Comment by camjackson** [comment]
This probably needs a review for two reasons:
1. Someone should do a code review of the whole [rabblerouser-infra](https://github.com/rabblerouser/rabblerouser-infra) repo to make sure it doesn't suck.
2. Someone else should run it to make sure it works, and that the instructions are right.

They could both be done by the same person.
