### ISSUE TITLE
RFC: Infrastructure management

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#91]
This issue is not so much to discuss what actual infrastructure might look like. It's more to talk about how infrastructure could be managed for all the various orgs using Rabble Rouser. E.g:
 - How does a new org get their infra set up?
 - How do we roll out changes to infra to our users?
 - How do orgs scale their infra?

Criteria:
 - All infrastructure should be automated and defined as code
 - It should be easy for new orgs to get set up, even if they have no technical staff
 - It should be easy for orgs to upgrade their infrastructure as we release new code
 - ???

**Comment by camjackson** [comment]
A proposal:

## Core tool: terraform

Terraform seems the obvious choice as the core tool. It's nicer to work with than cloud formation, and we could use it to provision in places other than AWS. I'm not aware of what other tools might be realistic competitors to it, other than rolling our own set of tools using the AWS CLI or SDKs, which seems like a recipe for pain.

There are two tricky parts to terraform: state management and secret management.

#### State management

Terraform doesn't inspect your actual infrastructure and keep it in sync with your code. Instead it writes the state of your infrastructure to a file, and uses that as the source of truth. So making manual changes to terraform-owned resources will break things, although manual changes to automated infra is a big no-no anyway, so in some ways this just enforces that

The other tricky question is what to do with that state file. The official docs recommend that you check it into source control, but we probably shouldn't do that because: a) it reveals more information to potential hackers than is necessary; b) there are certain terraform operations that can result in secrets (e.g. DB passwords) ending up in the state file; c) We're going to have `n` deployments which aren't controlled by us, most of them without ops staff to manage them, and those orgs will need an easy way to manage their state files.

Solution: Terraform now supports [remote state](https://www.terraform.io/docs/state/remote/index.html) which basically means that the state file goes _(hand wave)_ somewhere else. For example, you can configure it to go [in an S3 bucket](https://www.terraform.io/docs/state/remote/s3.html), which can have versioning on it, have access locked down, etc etc. I _think_ this could work pretty well for us.

More information in these blog posts: [one](http://code.hootsuite.com/how-to-use-terraform-and-remote-state-with-s3/), [two](https://charity.wtf/2016/03/30/terraform-vpc-and-why-you-want-a-tfstate-file-per-env/).

#### Secret management

This is something I haven't really dug into yet. If the terraform state file is sufficiently protected, then that may end up being a good place for secrets to go? Maybe it's [AWS KMS](https://aws.amazon.com/kms/)? Maybe [Hashicorp Vault](https://www.vaultproject.io/)? (On that note, we might want to look at Hashicorp's [Atlas](https://www.hashicorp.com/atlas.html), which is a commercial tool, but might solve some of these problems for us.)

## Implementation

Here's an example of what we could build with terraform:
1. We write terraform modules that describe all the core infrastructure that a Rabble Rouser deployment needs. E.g. Instances, networking, storage, etc. Nothing that is specific to any particular deployment goes into this codebase, and no user org should ever need to look at it.
2. Tool `<X>`. There are a number of shapes this could take, but it's basically a thing that makes it easy to run the code from (1), parameterised with your org-specific variables, and manage the resulting terraform state file.
   
   2.1. _Basic:_ A template terraform project which loads and runs the modules from (1). You're responsible for filling in the blanks, maintaining your fork of the template, and figuring out what to do with the terraform state file.
   
   2.2. _Intermediate:_ Similar to the above, but there are helper scripts that automate everything. You still need to be comfortable with git and the command line, and you might need to install terraform yourself, but you don't ever have to get your hands dirty with it.
   
   2.3 _Fancy:_ Some GUI tool that asks for bare minimum user input (AWS creds only?) and does everything for you. It generates the necessary terraform scaffolding code. It creates an S3 bucket and configures terraform to store your infra state in it. It randomly generates credentials and puts them... somewhere safe. It executes terraform for you. It mows your lawn and sings your children to sleep.

I think any of the above tools could be made to support the use cases that we'll have:
- Creating a new environment: as described above
- Getting updates to the core modules: In every case, the code that the client has is a thin wrapper, and can be made to pull down new versions of the core modules as we publish them
- Adding a new plugin: You edit your code and re-run terraform, or run a shell command, or click a button, and your new plugin will be deployed into your environment.
- What are our other main user flows?

**Comment by phazel** [comment]
Cam go to sleep

**Comment by camjackson** [comment]
Ok.
